-- by Jeremy Posada
-- V1 - Esquema inicial

-- ---------------------------------------------------------------- cuentas ---
CREATE TABLE app_users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(200) NOT NULL,
    email          VARCHAR(200) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    role           VARCHAR(20)  NOT NULL,
    blocked_until  TIMESTAMPTZ,
    blocked_reason VARCHAR(300),
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_app_users_email UNIQUE (email),
    CONSTRAINT ck_app_users_role CHECK (role IN ('ADMIN', 'BIBLIOTECARIO'))
);

CREATE INDEX idx_app_users_blocked_until ON app_users (blocked_until);

-- ---------------------------------------------------------------- catalogo ---
CREATE TABLE books (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                  VARCHAR(300) NOT NULL,
    author                 VARCHAR(300) NOT NULL,
    isbn                   VARCHAR(20)  NOT NULL,
    publication_year       INTEGER,
    status                 VARCHAR(20)  NOT NULL DEFAULT 'DISPONIBLE',
    cover_url              VARCHAR(500),
    enriched_from_external BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ  NOT NULL,
    updated_at             TIMESTAMPTZ  NOT NULL,
    version                BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_books_isbn UNIQUE (isbn),
    CONSTRAINT ck_books_status CHECK (status IN ('DISPONIBLE', 'PRESTADO', 'RESERVADO'))
);

CREATE INDEX idx_books_status ON books (status);
CREATE INDEX idx_books_title  ON books (LOWER(title));
CREATE INDEX idx_books_author ON books (LOWER(author));

-- Temas / materias que llegan enriquecidos desde Open Library
CREATE TABLE book_subjects (
    book_id BIGINT       NOT NULL,
    subject VARCHAR(200) NOT NULL,
    CONSTRAINT fk_book_subjects_book FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE
);

CREATE INDEX idx_book_subjects_book ON book_subjects (book_id);

-- --------------------------------------------------------------- prestamos ---
CREATE TABLE loans (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id                BIGINT       NOT NULL,
    borrower_name          VARCHAR(200) NOT NULL,
    borrower_email         VARCHAR(200) NOT NULL,
    loan_date              DATE         NOT NULL,
    due_date               DATE         NOT NULL,
    return_date            DATE,
    reminder_sent_at       TIMESTAMPTZ,
    overdue_notice_sent_at TIMESTAMPTZ,
    created_at             TIMESTAMPTZ  NOT NULL,
    version                BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_loans_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT ck_loans_due_after_loan CHECK (due_date >= loan_date)
);

CREATE INDEX idx_loans_borrower_email ON loans (LOWER(borrower_email));
CREATE INDEX idx_loans_book           ON loans (book_id);
-- Consultas del scheduler: prestamos activos ordenados por vencimiento
CREATE INDEX idx_loans_active_due     ON loans (due_date) WHERE return_date IS NULL;
-- Un libro no puede tener dos prestamos activos al mismo tiempo
CREATE UNIQUE INDEX uk_loans_active_book ON loans (book_id) WHERE return_date IS NULL;

-- ---------------------------------------------------------- lista de espera ---
CREATE TABLE reservations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id         BIGINT       NOT NULL,
    requester_email VARCHAR(200) NOT NULL,
    requested_at    TIMESTAMPTZ  NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    notified_at     TIMESTAMPTZ,
    CONSTRAINT fk_reservations_book FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
    CONSTRAINT ck_reservations_status CHECK (status IN ('PENDIENTE', 'NOTIFICADO', 'CANCELADO', 'CUMPLIDO'))
);

CREATE INDEX idx_reservations_queue ON reservations (book_id, status, requested_at);
CREATE INDEX idx_reservations_email ON reservations (LOWER(requester_email));
-- Nadie puede estar dos veces en la fila del mismo libro
CREATE UNIQUE INDEX uk_reservations_active
    ON reservations (book_id, LOWER(requester_email))
    WHERE status IN ('PENDIENTE', 'NOTIFICADO');
